<script type="text/x-magento-init">
    {
        "*": {
            "CarlosReynosa_OsanoCookieConsent/js/init": {
                "palette": {
                    "popup": {
                        "background": "#000"
                    },
                    "button": {
                        "background": "#f1d600"
                    }
                }
            }
        }
    }
</script>
